<a href="https://colab.research.google.com/github/haerinHong/Spring_2021/blob/main/%ED%98%84%ED%96%89%ED%99%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

Mounted at /gdrive

In [11]:
file1 = '/gdrive/MyDrive/Colab Notebooks/기존 AS_IS 공통.xlsx'
file2 = '/gdrive/MyDrive/Colab Notebooks/리버스대상.xlsx'

In [6]:
asis = pd.read_excel(file1)
asis.head()

           테이블명    속성명    엔터티명           컬럼명  ... 암호화방법  Level  컬럼 순서 컬럼 표준화
0        COPY_T     NO  COPY_T            NO  ...   NaN    NaN      1      0
1        COPY_T    NO2  COPY_T           NO2  ...   NaN    NaN      2      0
2  DA_ATTRIBUTE   속성ID      속성        ATTRID  ...   NaN    NaN      1      0
3  DA_ATTRIBUTE  기간만료일      속성   EXPIREDDATE  ...   NaN    NaN      2      0
4  DA_ATTRIBUTE   등록일자      속성  REGISTERDATE  ...   NaN    NaN      3      0

[5 rows x 22 columns]

In [12]:
rev = pd.read_excel(file2)
rev.head()

                테이블명     속성명               엔터티명  ... Level  컬럼 순서  컬럼 표준화
0        abb_comp_01      nm        abb_comp_01  ...   NaN      1       0
1        abb_comp_02  dbl_nm        abb_comp_02  ...   NaN      1       0
2        abb_comp_03      nm        abb_comp_03  ...   NaN      1       0
3        abb_comp_03     abb        abb_comp_03  ...   NaN      2       0
4  common_temp_table   objid  common_temp_table  ...   NaN      1       0

[5 rows x 22 columns]

In [13]:
asis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 915 entries, 0 to 914
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   테이블명         915 non-null    object
 1   속성명          915 non-null    object
 2   엔터티명         915 non-null    object
 3   컬럼명          915 non-null    object
 4   테이블 보조명      667 non-null    object
 5   테이블 단계       915 non-null    int64
 6   테이블 Level    915 non-null    int64
 7   테이블 표준화      915 non-null    object
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  데이터타입        807 non-null    object
 11  길이           754 non-null    float64
 12  컬럼 정의        57 non-null     object
 13  PK           915 non-null    object
 14  컬럼 CharUsed  915 non-null    object
 15  개인정보여부       915 non-null    object
 16  정보보호등급       0 non-null      float64
 17  암호화여부        915 non-null    object
 18  암호화방법        0 non-null      float64
 19  Level        0 non-null      float64
 20  컬럼 순서        915 non-null    int64
 21  컬럼 표준화       915 non-null    int64
dtypes: float64(6), int64(4), object(12)
memory usage: 157.4+ KB

In [14]:
rev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11561 entries, 0 to 11560
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   테이블명         11561 non-null  object
 1   속성명          11561 non-null  object
 2   엔터티명         11561 non-null  object
 3   컬럼명          11561 non-null  object
 4   테이블 보조명      0 non-null      float64
 5   테이블 단계       11561 non-null  int64
 6   테이블 Level    11561 non-null  int64
 7   테이블 표준화      11561 non-null  object
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  데이터타입        11561 non-null  object
 11  길이           9981 non-null   float64
 12  컬럼 정의        11561 non-null  object
 13  PK           11561 non-null  object
 14  컬럼 CharUsed  11561 non-null  object
 15  개인정보여부       11561 non-null  object
 16  정보보호등급       0 non-null      float64
 17  암호화여부        11561 non-null  object
 18  암호화방법        0 non-null      float64
 19  Level        0 non-null      float64
 20  컬럼 순서        11561 non-null  int64
 21  컬럼 표준화       11561 non-null  int64
dtypes: float64(7), int64(4), object(11)
memory usage: 1.9+ MB

In [16]:
print('asis shape ' , asis.shape)
print('rev shape ', rev.shape)

asis shape  (915, 22)
rev shape  (11561, 22)

In [18]:
s1 = 'copy_t'
s1.upper()

'COPY_T'

In [45]:
# 일단 따로 추출한 다음에 비교를 해야할거 같다..?

SyntaxError: ignored

In [51]:
asis_col = asis['테이블명'].unique().tolist()
asis_col

['COPY_T',
 'DA_ATTRIBUTE',
 'DA_COLUMN',
 'DA_ENTITY',
 'DA_MODELSTRU',
 'DA_TABLE',
 'DQ업무영역',
 'DQ업무영역_1',
 'IMSI_MD_UDP_REQ',
 'MAU_PRV_INFO',
 'MAU_PRV_REL',
 'MAU_ROLE_INFO',
 'MAU_ROLE_PRV_REL',
 'MAU_ROLE_REL',
 'MD_COL',
 'MD_INST',
 'MD_OBJ',
 'MD_UDP_CLSS',
 'MD_UDP_DEF',
 'MD_UDP_GRP',
 'MD_UDP_REQ_CONTENTS',
 'MD_UDP_VAL',
 'MM_ATTACH_FILE',
 'MM_BIZ_AREA',
 'MM_CODE',
 'MM_LOGIN_HIST',
 'MM_MAPBIZOBJ',
 'MM_NOTICE',
 'MM_NOTICE_FILE',
 'MMLICENSE',
 'MMMASTER',
 'MS_CFG_CLS',
 'MS_CFG_LST_VAL',
 'MS_CODE',
 'MS_DB_CONFIG',
 'MS_DB_SRC_LOG',
 'MS_LOCALE',
 'MS_MDL_CONFIG',
 'MS_MSG',
 'MS_STD_CONFIG',
 'MS_TERM',
 'MS_USR_LANG_MAP',
 'MSG_ATTACH',
 'MSG_LINE',
 'MSG_SIGN_RSLT',
 'MSG_SIGN_RSLT_DTL',
 'MSG_STEP',
 'MSG_TARGET',
 'Part',
 'PRE_MSG_RSLT',
 'REQ_DOC_INFO',
 'RM_COL_INF',
 'RM_OBJ_INF',
 'STD_CD_VAL',
 'STD_CODE',
 'STD_DIC',
 'STD_REQ_CONTENTS',
 'USER_OBJ_MAP',
 'USR_ALLOC',
 'USR_DAILY_ALERT',
 'USR_DEPT',
 'USR_EVENT',
 'USR_GROUP',
 'USR_GROUP_MEMBER',
 'USR_JOB_EVENT',
 'USR_MENU',
 'USR_MENUGRP',
 'USR_PRIV',
 'USR_PRIV_SCR_OBJ',
 'USR_RCV_EVENT',
 'USR_ROLE',
 'USR_ROLE_PRIV',
 'USR_SCR_OBJ',
 'USR_USAGE_LOG',
 'USR_USER',
 'USR_USR_ALERT',
 '게시물',
 '메타표준오브젝트',
 '모델영역',
 '물리테이블',
 '부서',
 '사용자',
 '역할',
 '응용분류체계',
 '인사정보',
 '인사정보_1',
 '작업',
 '조직정보',
 '주제영역',
 '주제영역_1',
 '표준분류체계',
 '표준분류체계_1']

In [47]:
rev[rev['테이블명'] == 'copy_t']

     테이블명  속성명    엔터티명  컬럼명  테이블 보조명  ...  암호화여부  암호화방법 Level  컬럼 순서  컬럼 표준화
8  copy_t   no  copy_t   no      NaN  ...      N    NaN   NaN      1       0
9  copy_t  no2  copy_t  no2      NaN  ...      N    NaN   NaN      2       0

[2 rows x 22 columns]

In [52]:
if 'COPY_T' in asis_col :
  print('yes')

else : print('no')

yes

In [57]:
# 공통영역에 해당하는 리버스 데이터를 거르기 위한 작업
# filte_rev에 공통영역에 해당하는 리버스 데이터를 넣음. 스키마만 따기 위한 작업
filter_rev = pd.DataFrame(rev[rev['테이블명'] == ''])
filter_rev

Empty DataFrame
Columns: [테이블명, 속성명, 엔터티명, 컬럼명, 테이블 보조명, 테이블 단계, 테이블 Level, 테이블 표준화, Unnamed: 8, Unnamed: 9, 데이터타입, 길이, 컬럼 정의, PK, 컬럼 CharUsed, 개인정보여부, 정보보호등급, 암호화여부, 암호화방법, Level, 컬럼 순서, 컬럼 표준화]
Index: []

In [96]:
rev_col = rev['테이블명'].unique().tolist()
for i in range(len(rev_col)) :
  rev_col[i] = rev_col[i].upper()

rev_col

['ABB_COMP_01',
 'ABB_COMP_02',
 'ABB_COMP_03',
 'COMMON_TEMP_TABLE',
 'CONCEPT_LOGICAL_MAP',
 'COPY_T',
 'DA_CODE',
 'DA_LOCALE',
 'DA_OPTIONS',
 'DA_TERM',
 'DAM_ALGN_MAP',
 'DF_REQ_FLOW',
 'DF_REQ_OBJ',
 'DF_SYS_SYNONYM',
 'ENC_ARGUMENTS',
 'ENC_COL_COMMENTS',
 'ENC_CONS_COLUMNS',
 'ENC_CONSTRAINTS',
 'ENC_DATA_FILES',
 'ENC_DB_LINKS',
 'ENC_DEPENDENCIES',
 'ENC_FREE_SPACE',
 'ENC_IND_COLUMNS',
 'ENC_IND_EXPRESSIONS',
 'ENC_IND_PARTITIONS',
 'ENC_IND_SUBPARTITIONS',
 'ENC_INDEXES',
 'ENC_MVIEW_DETAIL_RELATIONS',
 'ENC_MVIEWS',
 'ENC_OBJECTS',
 'ENC_PART_INDEXES',
 'ENC_PART_KEY_COLUMNS',
 'ENC_PART_TABLES',
 'ENC_PRDT_CMPNT_VERSION',
 'ENC_PROCEDURES',
 'ENC_SEGMENT_STATISTICS',
 'ENC_SEGMENTS',
 'ENC_SEQUENCES',
 'ENC_SNAPSHOT_LOGS',
 'ENC_SOURCE',
 'ENC_SUBPART_KEY_COLUMNS',
 'ENC_SYNONYMS',
 'ENC_TAB_COLUMNS',
 'ENC_TAB_COMMENTS',
 'ENC_TAB_PARTITIONS',
 'ENC_TAB_SUBPARTITIONS',
 'ENC_TABLES',
 'ENC_TABLESPACES',
 'ENC_TEMP_FILES',
 'ENC_TRIGGERS',
 'ENC_USERS',
 'ENC_V$PARAMETER',
 'ENC_V$TEMP_EXTENT_POOL',
 'ENC_VIEWS',
 'IMSI_BIZ_RULE_REQ',
 'IMSI_CD_INST_INFO',
 'IMSI_CMPLX_ANLY',
 'IMSI_CODE_DIST_REQ',
 'IMSI_CODE_INFO',
 'IMSI_CODE_INST_MAPPING',
 'IMSI_DBLNK_JOB_REQ',
 'IMSI_DBTODB_GAP',
 'IMSI_END_MNG_STD_DIC',
 'IMSI_MD_MDL_CHG_COL',
 'IMSI_MD_MDL_CHG_REQ_COL',
 'IMSI_MD_MDL_CHG_REQ_TBL',
 'IMSI_MD_MDL_CHG_TBL',
 'IMSI_MDB_ACCT_GRANT_JOB_REQ',
 'IMSI_MDB_ACCT_JOB_REQ',
 'IMSI_MDB_GAP_ATTR_DTL',
 'IMSI_MDB_GAP_OBJ_DTL',
 'IMSI_MDB_JOB_REQ_DDL',
 'IMSI_MDB_MDL_VRFY_RSLT',
 'IMSI_MDL_DB_GAP_INFO',
 'IMSI_MDL_GAP_ATRCOL',
 'IMSI_MDL_GAP_ENTTAB',
 'IMSI_MDL_GAP_INDEX',
 'IMSI_MDL_GAP_INDEX_COL',
 'IMSI_MDQ_CTQ',
 'IMSI_MDQ_JOB',
 'IMSI_MDQ_JOB_DTL',
 'IMSI_MDQ_PROFILE_ITEM',
 'IMSI_MDQ_PROFILE_TYPE',
 'IMSI_MDQ_TABLES',
 'IMSI_STD_DIC_REQ',
 'IMSI_STD_DIC_REQ_CD_VAL',
 'IMSI_STD_DIC_REQ_LISTCD_VAL',
 'IMSI_STD_DOM_CONV',
 'IMSI_TERM_INFO',
 'IMSI_USR_DEPT_REG',
 'IMSI_USR_USER_REG',
 'IMSI_WORD_INFO',
 'ITF_REQ_COLUMN',
 'ITF_REQ_TABLE',
 'LOCK_MDL_LIST',
 'MA_ANAL_SVR',
 'MA_APP_AREA',
 'MA_APP_AREA_DETAIL',
 'MA_APP_MAP_REL',
 'MA_APPACCT_MAP',
 'MA_CALL_NODE',
 'MA_CALLMTH',
 'MA_CALLMTH_ARG',
 'MA_CBL_CMD_DTL',
 'MA_CMMT_INFO',
 'MA_CMMT_ITEM',
 'MA_CMS_REL',
 'MA_CMS_REL_DETAIL',
 'MA_CONTENT',
 'MA_DIR',
 'MA_FILE',
 'MA_FILE_ACTION',
 'MA_FILE_DESC',
 'MA_INC',
 'MA_JOB_LOG',
 'MA_JOB_LOG_SUMMARY',
 'MA_LIBDIC',
 'MA_LOGIC',
 'MA_LOGIC_DTL',
 'MA_MATRIX_FLASH',
 'MA_MIPLATFORM',
 'MA_MYMAC_PGM_INFO',
 'MA_NODE',
 'MA_OBJ_REL',
 'MA_PREPERENCE_FILTER',
 'MA_REL_SQL',
 'MA_SQL_CLAUSE',
 'MA_SQL_HINT',
 'MA_SQL_NODE',
 'MA_SQL_NODE_OP',
 'MA_SQL_OBJ',
 'MA_SQL_SUBSQL',
 'MA_SRC_OBJ',
 'MA_STATISTIC',
 'MA_TDF_BODY',
 'MA_TDF_HDR',
 'MA_UNKNOWN',
 'MA_USE_OBJ_MAP',
 'MA_USER_CONFIG',
 'MAQ_AQI',
 'MAQ_ISPT',
 'MAQ_ISPT_ERROR',
 'MAQ_ISPT_FILE',
 'MAQ_ISPT_FILE_RULE',
 'MAQ_ISPT_FNL_RSLT',
 'MAQ_ISPT_RSLT',
 'MAQ_ISPT_RSLT_HK',
 'MAQ_ISPT_RULE',
 'MAQ_RULE',
 'MAQ_RULE_AQI',
 'MAQ_RULESET',
 'MAQ_RULESET_RULE',
 'MAQ_SQL',
 'MAQ_SQLINFO',
 'MAQ_UNITTEST_RSLT_HK',
 'MATRIX_TEMP',
 'MCS_AGENT_INF',
 'MCS_ALT_AUDIT',
 'MCS_ALT_AUDIT_ALL_OPTS',
 'MCS_ALT_COLUMNS',
 'MCS_ALT_COMMENTS',
 'MCS_ALT_COMPRESSION_TABLES',
 'MCS_ALT_CONSTRAINT_COLUMNS',
 'MCS_ALT_CONSTRAINT_RELATED',
 'MCS_ALT_CONSTRAINTS',
 'MCS_ALT_DATA_PORTS',
 'MCS_ALT_DATABASE',
 'MCS_ALT_DATABASE_LINKS',
 'MCS_ALT_DIRECTORIES',
 'MCS_ALT_DN_USERS',
 'MCS_ALT_DUMMY',
 'MCS_ALT_ENCRYPTED_COLUMNS',
 'MCS_ALT_GRANT_OBJECT',
 'MCS_ALT_GRANT_SYSTEM',
 'MCS_ALT_INDEX_COLUMNS',
 'MCS_ALT_INDEX_PARTITIONS',
 'MCS_ALT_INDEX_RELATED',
 'MCS_ALT_INDICES',
 'MCS_ALT_JOBS',
 'MCS_ALT_LIBRARIES',
 'MCS_ALT_LOBS',
 'MCS_ALT_MATERIALIZED_VIEWS',
 'MCS_ALT_PACKAGE_PARAS',
 'MCS_ALT_PACKAGE_PARSE',
 'MCS_ALT_PACKAGE_RELATED',
 'MCS_ALT_PACKAGES',
 'MCS_ALT_PART_INDICES',
 'MCS_ALT_PART_KEY_COLUMNS',
 'MCS_ALT_PART_LOBS',
 'MCS_ALT_PART_TABLES',
 'MCS_ALT_PASSWORD_HISTORY',
 'MCS_ALT_PASSWORD_LIMITS',
 'MCS_ALT_PRIVILEGES',
 'MCS_ALT_PROC_PARAS',
 'MCS_ALT_PROC_PARSE',
 'MCS_ALT_PROC_RELATED',
 'MCS_ALT_PROCEDURES',
 'MCS_ALT_RECYCLEBIN',
 'MCS_ALT_REPL_HOSTS',
 'MCS_ALT_REPL_ITEMS',
 'MCS_ALT_REPL_OFFLINE_DIR',
 'MCS_ALT_REPL_OLD_COLUMNS',
 'MCS_ALT_REPL_OLD_INDEX_COLUMNS',
 'MCS_ALT_REPL_OLD_INDICES',
 'MCS_ALT_REPL_OLD_ITEMS',
 'MCS_ALT_REPL_RECOVERY_INFOS',
 'MCS_ALT_REPLICATIONS',
 'MCS_ALT_SECURITY',
 'MCS_ALT_SYNONYMS',
 'MCS_ALT_TABLE_PARTITIONS',
 'MCS_ALT_TABLE_SIZE',
 'MCS_ALT_TABLES',
 'MCS_ALT_TBS_USERS',
 'MCS_ALT_TRIGGER_DML_TABLES',
 'MCS_ALT_TRIGGER_STRINGS',
 'MCS_ALT_TRIGGER_UPDATE_COLUMNS',
 'MCS_ALT_TRIGGERS',
 'MCS_ALT_USER_ROLES',
 'MCS_ALT_USERS',
 'MCS_ALT_V_DATABASE',
 'MCS_ALT_V_DATAFILES',
 'MCS_ALT_V_DATATYPE',
 'MCS_ALT_V_INDEX',
 'MCS_ALT_V_MEM_TABLESPACES',
 'MCS_ALT_V_MEMTBL_INFO',
 'MCS_ALT_V_PROPERTY',
 'MCS_ALT_V_SEQ',
 'MCS_ALT_V_TABLESPACES',
 'MCS_ALT_V_TSSEGS',
 'MCS_ALT_V_UDSEGS',
 'MCS_ALT_V_USAGE',
 'MCS_ALT_V_VERSION',
 'MCS_ALT_VIEWS',
 'MCS_ALT_VIEWS_PARSE',
 'MCS_ALT_VIEWS_RELATED',
 'MCS_ALT_X_SEGMENT',
 'MCS_ALT_XA_HEURISTIC_TRANS',
 'MCS_DB2UDB_SYSCOLUMNS',
 'MCS_DB2UDB_SYSINDEXCOLUSE',
 'MCS_DB2UDB_SYSINDEXES',
 'MCS_DB2UDB_SYSKEYCOLUSE',
 'MCS_DB2UDB_SYSSCHEMATA',
 'MCS_DB2UDB_SYSSEQUENCES',
 'MCS_DB2UDB_SYSTABCONST',
 'MCS_DB2UDB_SYSTABLES',
 'MCS_DB2UDB_SYSTABLESPACES',
 'MCS_DB2UDB_SYSTRIGGERS',
 'MCS_DB2UDB_VIEWS',
 'MCS_HBASE_COLUMNFAMILY',
 'MCS_HBASE_COLUMNS',
 'MCS_HBASE_FUNCS',
 'MCS_HBASE_INDEX',
 'MCS_HBASE_SCHEMA',
 'MCS_HBASE_SEQUENCE',
 'MCS_HBASE_TABLES',
 'MCS_HBASE_VIEWS',
 'MCS_JDBC_MAP',
 'MCS_MSS_ACCT',
 'MCS_MSS_ALLOCATION_UNITS',
 'MCS_MSS_CHECK_CONSTRAINTS',
 'MCS_MSS_COLUMNS',
 'MCS_MSS_DATABASE_FILES',
 'MCS_MSS_DATABASE_PRINCIPALS',
 'MCS_MSS_DEFAULT_CONSTRAINTS',
 'MCS_MSS_EXTENDED_PROPERTIES',
 'MCS_MSS_FOREIGN_KEYS',
 'MCS_MSS_INDEX_COLUMNS',
 'MCS_MSS_INDEXES',
 'MCS_MSS_KEY_CONSTRAINTS',
 'MCS_MSS_OBJECTS',
 'MCS_MSS_PARTITION_FUNCTIONS',
 'MCS_MSS_PARTITION_RANGE_VALUES',
 'MCS_MSS_PARTITION_SCHEMES',
 'MCS_MSS_PARTITIONS',
 'MCS_MSS_SCHEMAS',
 'MCS_MSS_SEQUENCES',
 'MCS_MSS_SERVER_PRINCIPALS',
 'MCS_MSS_SERVERS',
 'MCS_MSS_SQL_EXP_DEPENDS',
 'MCS_MSS_SQL_MODULES',
 'MCS_MSS_SRC',
 'MCS_MSS_SYSCOLUMNS',
 'MCS_MSS_SYSCOMMENTS',
 'MCS_MSS_SYSCONFIGURES',
 'MCS_MSS_SYSCONSTRAINTS',
 'MCS_MSS_SYSCURCONFIGS',
 'MCS_MSS_SYSDEPENDS',
 'MCS_MSS_SYSFILES',
 'MCS_MSS_SYSINDEXES',
 'MCS_MSS_SYSINDEXKEYS',
 'MCS_MSS_SYSLOGINS',
 'MCS_MSS_SYSOBJECTS',
 'MCS_MSS_SYSREFERENCES',
 'MCS_MSS_SYSREMOTELOGINS',
 'MCS_MSS_SYSSERVERS',
 'MCS_MSS_SYSTYPES',
 'MCS_MSS_SYSUSERS',
 'MCS_MSS_TABLES',
 'MCS_MSS_TEMPSRC',
 'MCS_MSS_TEMPTABLES',
 'MCS_MY_COLLATIONS',
 'MCS_MY_COLUMNS',
 'MCS_MY_KEY_COLUMN_USAGE',
 'MCS_MY_PARAMETERS',
 'MCS_MY_ROUTINES',
 'MCS_MY_SCHEMATA',
 'MCS_MY_STATISTICS',
 'MCS_MY_TABLES',
 'MCS_MY_TABLESPACES',
 'MCS_MY_TBL_CONSTRAINTS',
 'MCS_MY_TRIGGERS',
 'MCS_MY_VIEWS',
 'MCS_PG_ATTRDEF',
 'MCS_PG_ATTRIBUTE',
 'MCS_PG_AUTHID',
 'MCS_PG_CLASS',
 'MCS_PG_COLUMNS',
 'MCS_PG_CONSTRAINT',
 'MCS_PG_DEPEND',
 'MCS_PG_DESCRIPTION',
 'MCS_PG_INDEX',
 'MCS_PG_INFO_SCHEMA_COLUMNS',
 'MCS_PG_INFO_SCHEMA_SEQUENCES',
 'MCS_PG_INHERITS',
 'MCS_PG_LANGUAGE',
 'MCS_PG_NAMESPACE',
 'MCS_PG_PROC',
 'MCS_PG_SEQUENCES',
 'MCS_PG_SETTINGS',
 'MCS_PG_STATIO_ALL_TABLES',
 'MCS_PG_TABLES',
 'MCS_PG_TABLESPACE',
 'MCS_PG_TRIGGER',
 'MCS_PG_TYPE',
 'MCS_PG_USER',
 'MCS_PG_VIEWS',
 'MCS_RS_ATTRIBUTE',
 'MCS_RS_CLASS_INFO',
 'MCS_RS_TBL_PERM',
 'MCS_SY_ASE_SYSCOLUMNS',
 'MCS_SY_ASE_SYSCONFIGURES',
 'MCS_SY_ASE_SYSCURCONFIGS',
 'MCS_SY_ASE_SYSDEPENDS',
 'MCS_SY_ASE_SYSDEVICES',
 'MCS_SY_ASE_SYSINDEXES',
 'MCS_SY_ASE_SYSPARTITIONKEYS',
 'MCS_SY_ASE_SYSPARTITIONS',
 'MCS_SY_ASE_SYSREFERENCES',
 'MCS_SY_ASE_SYSTYPES',
 'MCS_SY_ASE_SYSUSAGES',
 'MCS_SY_IQ_PARAM',
 'MCS_SY_IQ_SYSCHECK',
 'MCS_SY_IQ_SYSCOLUMN',
 'MCS_SY_IQ_SYSCOLUMNS',
 'MCS_SY_IQ_SYSCONSTRAINT',
 'MCS_SY_IQ_SYSFILE',
 'MCS_SY_IQ_SYSFOREIGNKEY',
 'MCS_SY_IQ_SYSINDEX',
 'MCS_SY_IQ_SYSINDEXES',
 'MCS_SY_IQ_SYSINFO',
 'MCS_SY_IQ_SYSIQFILE',
 'MCS_SY_IQ_SYSIQINFO',
 'MCS_SY_IQ_SYSIQJOININDEX',
 'MCS_SY_IQ_SYSIQJOINIXCOLUMN',
 'MCS_SY_IQ_SYSIXCOL',
 'MCS_SY_IQ_SYSPROCPARMS',
 'MCS_SY_IQ_SYSTABLE',
 'MCS_SY_IQ_SYSTRIGGER',
 'MCS_SY_SYSCOMMENTS',
 'MCS_SY_SYSCONSTRAINTS',
 'MCS_SY_SYSLOGINS',
 'MCS_SY_SYSOBJECTS',
 'MCS_SY_SYSREMOTELOGINS',
 'MCS_SY_SYSSERVERS',
 'MCS_SY_SYSUSERS',
 'MCS_USER_JOB_GRP',
 'MCS_USER_JOB_SQL',
 'MCS_VT_COLUMNS',
 'MCS_VT_COMMENTS',
 'MCS_VT_CONSTRAINT_COLUMNS',
 'MCS_VT_FUNCTION_PARAMETERS',
 'MCS_VT_PROJECTION_COLUMNS',
 'MCS_VT_PROJECTIONS',
 'MCS_VT_SCHEMATA',
 'MCS_VT_SEQUENCES',
 'MCS_VT_TABLE_CONSTRAINTS',
 'MCS_VT_TABLES',
 'MCS_VT_TEXT_INDICES',
 'MCS_VT_TYPES',
 'MCS_VT_USER_FUNCTIONS',
 'MCS_VT_USER_PROCEDURES',
 'MCS_VT_VIEW_COLUMNS',
 'MCS_VT_VIEW_TABLES',
 'MCS_VT_VIEWS',
 'MD_ACCT',
 'MD_ANAL_LOG',
 'MD_ARG',
 'MD_CHG_MNG_COL',
 'MD_COL',
 'MD_COL_ADDN',
 'MD_COL_ADDN_DEF',
 'MD_COL_COMP',
 'MD_COL_STATISTICS',
 'MD_CONST',
 'MD_CPU_USE_STATISTICS',
 'MD_DB',
 'MD_DB_PM_MAP',
 'MD_DBMS_OBJ_TYPE_DEF',
 'MD_DEP',
 'MD_DF',
 'MD_DF_ALLOC',
 'MD_DF_USG',
 'MD_ENTITY_OWNER',
 'MD_FEATURE_USE_STATISTICS',
 'MD_GAP_CLASS_HIST',
 'MD_GAP_EXCLUDED_TABLES',
 'MD_HIWATERMARK_STATISTICS',
 'MD_INST',
 'MD_ISSU_DTL',
 'MD_JOB',
 'MD_JOB_HIST',
 'MD_JOB_HIST_LOG',
 'MD_JOB_SCHD',
 'MD_LINK',
 'MD_LINK_LOGN',
 'MD_LOGICANAL',
 'MD_LSNR',
 'MD_MDL_APRV_REQ',
 'MD_MDL_APRV_REQ_ADDTN',
 'MD_MDL_APRV_REQ_ATRCOL',
 'MD_MDL_APRV_REQ_ENTTAB',
 'MD_MDL_APRV_REQ_PRTIDX',
 'MD_MDL_CHG_REQ_COL',
 'MD_MDL_CHG_REQ_TBL',
 'MD_MDL_COL_VALIDRULE',
 'MD_MDL_CONST',
 'MD_MDL_GAB_ALLOC_ACCT',
 'MD_MDL_GAB_INDEX',
 'MD_MDL_GAB_INDEX_COL',
 'MD_MDL_GAB_OBJ_DDL',
 'MD_MDL_GAP_ATRCOL',
 'MD_MDL_GAP_ENTTAB',
 'MD_MDL_GAP_PRTIDX',
 'MD_MDL_REQ',
 'MD_MDL_STORAGE',
 'MD_MDL_STORAGEEX',
 'MD_MNG_APPAREA',
 'MD_MNG_BR',
 'MD_MNG_MODEL',
 'MD_MNG_OBJ',
 'MD_MVIEW',
 'MD_MVIEW_DTL_REL',
 'MD_MVIEW_LOG',
 'MD_OBJ',
 'MD_OBJ_ADDN',
 'MD_OBJ_ADDN_DEF',
 'MD_OBJ_CHG_DTL',
 'MD_OBJ_PART',
 'MD_OBJ_REL',
 'MD_OBJANAL',
 'MD_OBJECT_STATISTICS',
 'MD_PARAM',
 'MD_PATCH_DTL',
 'MD_PROC',
 'MD_PROJECTION',
 'MD_PROJECTION_COL',
 'MD_REPRESOL_STATISTICS',
 'MD_SEG',
 'MD_SEG_STG_DTL',
 'MD_SEQ',
 'MD_SQLANAL',
 'MD_SRC',
 'MD_SVR',
 'MD_SVR_IP',
 'MD_SYNM',
 'MD_TAB_RTN',
 'MD_TEXT_INDICES',
 'MD_TRG',
 'MD_TS',
 'MD_TS_STG_DTL',
 'MD_VIEW',
 'MDB_ACCT_GRANT_HIST',
 'MDB_ACCT_GRANT_INFO',
 'MDB_ACCT_GRANT_JOB_REQ',
 'MDB_ACCT_ROLE',
 'MDB_ACCT_ROLE_MAP',
 'MDB_ACCT_STAT',
 'MDB_ACCT_USE_INFO',
 'MDB_DBLINK_REQ',
 'MDB_DDL_STRU_HIST',
 'MDB_DDL_SYNTX_HIST',
 'MDB_DDL_VAR_HIST',
 'MDB_GAP_ANL_TRGT',
 'MDB_GAP_ATTR_DTL',
 'MDB_GAP_CLASS',
 'MDB_GAP_CLASS_BAK',
 'MDB_GAP_CLASS_HIST',
 'MDB_GAP_CLASS_PROPERTY_HIST',
 'MDB_GAP_DATA_TYPE_RULE_BASE_HIST',
 'MDB_GAP_OBJ_DTL',
 'MDB_INDEX_COL',
 'MDB_INDEX_DB',
 'MDB_INDEX_DDL',
 'MDB_INDEX_JOB',
 'MDB_INDEX_MDL',
 'MDB_INDEX_OBJ_COL',
 'MDB_MDL_CHG_DDL',
 'MDB_MDL_MAP',
 'MDB_OBJ_DDL',
 'MDB_OBJ_DDL_ADDN',
 'MDB_OBJ_DDL_HIST',
 'MDB_PRTTP_DDL_INF',
 'MDB_TBL_DDL_MAP',
 'MDB_TBL_MAP',
 'MDL_AUTH_REQ_CONTENTS',
 'MDL_CHK_AREA',
 'MDL_CHK_ITEM',
 'MDL_CHK_ITEM_HIST',
 'MDL_CHK_RSLT',
 'MDL_UDP_SRCH_TRGT',
 'MDQ_ADDN_EXEC_INF',
 'MDQ_BIZ_RULE',
 'MDQ_BIZ_RULE_COL',
 'MDQ_BIZ_RULE_ERR_CNT',
 'MDQ_BIZ_RULE_RSLT',
 'MDQ_BIZ_RULE_RSLT_DATA',
 'MDQ_BIZ_RULE_SQL',
 'MDQ_BIZAREA',
 'MDQ_BIZAREA_ADDN',
 'MDQ_BR_COL',
 'MDQ_BR_CTQ',
 'MDQ_BR_ERROR_ANALYZE',
 'MDQ_BR_REQ',
 'MDQ_BR_REQ_INFO',
 'MDQ_CALENDAR_T',
 'MDQ_CD_TBL_INF',
 'MDQ_CD_TRGT_MAP',
 'MDQ_COL_DGNSS_ITEM_MAP',
 'MDQ_COLS',
 'MDQ_COPY_T',
 'MDQ_CTQ',
 'MDQ_CTQ_COL',
 'MDQ_DBMS',
 'MDQ_DGNSS_COLS',
 'MDQ_DGNSS_PTTRN',
 'MDQ_DGNSS_TABLES',
 'MDQ_DQI',
 'MDQ_DQI_LNG_MAP',
 'MDQ_EXCLUDE_INDCT_CLSFC_ITEM',
 'MDQ_FILE_LOG',
 'MDQ_IMSI_BATCH_CTQ_COL',
 'MDQ_IMSI_BR_ARC',
 'MDQ_IMSI_BR_CONSISTENCY',
 'MDQ_IMSI_BR_LAST',
 'MDQ_IMSI_BR_RI',
 'MDQ_IMSI_BR_SERIAL',
 'MDQ_IMSI_COL_DGNSS_ITEM_MAP',
 'MDQ_IMSI_COL_DGNSS_ITEM_UPLOAD',
 'MDQ_IMSI_DGNSS_TBL_UPLOAD',
 'MDQ_IMSI_INDCT_CLSFC_CRTR',
 'MDQ_INDCT_CLSFC_CRTR',
 'MDQ_JOB',
 'MDQ_JOB_DTL',
 'MDQ_JOB_FLOW',
 'MDQ_JOB_FLOW_EXEC_JOB',
 'MDQ_JOB_FLOW_LOG',
 'MDQ_JOB_LOG',
 'MDQ_JOB_LOG_DTL',
 'MDQ_MAPPING_BIZ_RULE_RSLT_DATA',
 'MDQ_MAPPING_RSLT_DATA',
 'MDQ_OBJ',
 'MDQ_PROFILE_CODE_MAP',
 'MDQ_PROFILE_ERROR_ANALYZE',
 'MDQ_PROFILE_ITEM',
 'MDQ_PROFILE_RSLT',
 'MDQ_PROFILE_SQL',
 'MDQ_PROFILING',
 'MDQ_RSLT_DATA',
 'MDQ_SELECT_COLS',
 'MDQ_SIGMA',
 'MDQ_STD_AREA',
 'MDQ_SURV_ANSWR',
 'MDQ_SURV_BIZAREA',
 'MDQ_SURV_INFO',
 'MDQ_SURV_ITEM',
 'MDQ_SURV_TMS',
 'MDQ_SURV_TRGT',
 'MDQ_TABLES',
 'MDQ_TABLES_PART',
 'MET_BIZ_AREA',
 'MET_BIZ_CLM',
 'MET_BIZ_TBL',
 'MET_CLASS',
 'MET_CLS_PRPT',
 'MET_CONN_LIST',
 'MET_CONNECTIONS',
 'MET_JOB',
 'MET_JOB_CLM',
 'MET_JOB_MACRO',
 'MET_JOB_PARAM',
 'MET_JOB_PARAM_PART',
 'MET_JOB_RN_HST',
 'MET_JOB_RN_HST_PART',
 'MET_JOB_RN_LOG',
 'MET_JOB_RN_LOG_PART',
 'MET_JOB_TBL',
 'MET_LAUNCHER_LOG',
 'MET_LAUNCHER_MEM_LOG',
 'MET_LAUNCHER_STATUS',
 'MET_OBJ_PRPT',
 'MET_OBJECTS',
 'MET_PROPERTIES',
 'MET_PRPT_LIST',
 'MET_RULE_CHK_SCRIPT',
 'MET_SQL_CDN_EXP',
 'MET_SQL_CLAUSE',
 'MET_SQL_CONDITION',
 'MET_SQL_EXPRESSION',
 'MET_SQL_STRUCT',
 'MET_STP_RN_HST',
 'MET_STP_RN_HST_PART',
 'MET_STP_SQL_HST',
 'MET_STP_SQL_HST_PART',
 'MET_VISUAL',
 'MM_CODE',
 'MM_DOMAIN',
 'MM_DOMAIN_GROUP',
 'MM_DOMAIN_INST',
 'MM_ENV',
 'MM_INFO_TYPE',
 'MM_INFO_TYPE_MAPPING',
 'MM_LOCALE',
 'MM_LOCALE_MESSAGE',
 'MM_LOGIN_HIST',
 'MM_MAPBIZOBJ',
 'MM_MENU_HIST',
 'MM_NOTICE',
 'MM_NOTICE_FILE',
 'MM_PERMISSION_STEP',
 'MM_USER_LOGIN_FAIL_INFO',
 'MMLICENSE',
 'MMMASTER',
 'MS_APRV_ERR_LOG',
 'MS_CODE',
 'MS_CODE_HIST',
 'MS_CONFIG',
 'MS_DSBD_INF',
 'MS_LOCALE',
 'MS_MSG',
 'MS_OBJ_REL',
 'MS_TASK_INFO',
 'MS_TASK_RSLT',
 'MS_TERM',
 'MS_TERM_HIST',
 'MS_UDP',
 'MS_UDP_CLS',
 'MS_UDP_LST_VAL',
 'MSG_ATTACH',
 'MSG_LINE',
 'MSG_LOG',
 'MSG_SIGN_RSLT',
 'MSG_SIGN_RSLT_DTL',
 'MSG_STEP',
 'MSG_TARGET',
 'MY_TODO',
 'REP_OWNER_INFO',
 'REQ_CHK_ITEM_HIST',
 'REQ_CHK_ITEM_VAR_HIST',
 'REQ_DOC_INFO',
 'RM_COL_INF',
 'RM_OBJ_INF',
 'RM_VER_INF',
 'SEQ_TAB',
 'SHARE_ENTITY_LIST',
 'SMPL_SR_REQ_COLUMN',
 'SMPL_SR_REQ_INFO',
 'SMPL_SR_REQ_TABLE',
 'SQL_CONN_HIST',
 'SQL_POLICY',
 'SQL_POLICY_TAB_COL',
 'SQL_QUERY_LOG',
 'STAT_CONF',
 'STD_AREA_DA_MAP',
 'STD_BAN',
 'STD_CD_AREA',
 'STD_CD_MD_COL_MAP',
 'STD_CD_VAL',
 'STD_CD_VAL_LOCALE',
 'STD_CD_VAL_REL',
 'STD_CODE',
 'STD_CODE_ADDN',
 'STD_CODE_DIST_REQ',
 'STD_CODE_LOCALE',
 'STD_CODE_PROPERTY',
 'STD_CODE_REFL_REQ',
 'STD_CODE_REL_USER',
 'STD_CONTENTS_MAP',
 'STD_DETAIL_RULE',
 'STD_DIC_DATA',
 'STD_DOM_CONV_REQ_CONTENTS',
 'STD_DOM_TYPE_TRANF',
 'STD_NAMING_RULE',
 'STD_NAMING_RULE_VERF',
 'STD_REQ_CD_MD_COL_MAP',
 'STD_REQ_CD_VAL',
 'STD_REQ_CONTENTS',
 'STD_REQ_TERM_COMP',
 'STD_REQUEST_INF',
 'STD_SQL',
 'STD_TERMS_ATTR_MAP',
 'STD_WORDS',
 'T_REQUEST',
 'TMD_ACCT',
 'TMD_ARG',
 'TMD_COL',
 'TMD_COL_COMP',
 'TMD_COL_STATISTICS',
 'TMD_CONST',
 'TMD_CPU_USE_STATISTICS',
 'TMD_DATABASE_VERSION',
 'TMD_DB',
 'TMD_DEP',
 'TMD_DF',
 'TMD_DF_ALLOC',
 'TMD_DF_USG',
 'TMD_FEATURE_USE_STATISTICS',
 'TMD_HIWATERMARK_STATISTICS',
 'TMD_LINK',
 'TMD_LINK_LOGN',
 'TMD_LOGICANAL',
 'TMD_MVIEW',
 'TMD_MVIEW_DTL_REL',
 'TMD_MVIEW_LOG',
 'TMD_OBJ',
 'TMD_OBJ_CHG_DTL',
 'TMD_OBJANAL',
 'TMD_OBJECT_STATISTICS',
 'TMD_PARAM',
 'TMD_PROC',
 'TMD_PROJECTION',
 'TMD_PROJECTION_COL',
 'TMD_REPRESOL_STATISTICS',
 'TMD_RVS_COLUMN',
 'TMD_RVS_TABLE',
 'TMD_SEG',
 'TMD_SEG_STG_DTL',
 'TMD_SEQ',
 'TMD_SQLANAL',
 'TMD_SRC',
 'TMD_SYNM',
 'TMD_TAB_RTN',
 'TMD_TEXT_INDICES',
 'TMD_TRG',
 'TMD_TS',
 'TMD_TS_STG_DTL',
 'TMD_VIEW',
 'TMP_ALL_REQ_INFO',
 'TMP_LONGTOVARCHAR',
 'TMP_USR_DEPT',
 'TOBE_TBL_JOB_MAP',
 'TTMD_TRG',
 'UI_LABEL',
 'UI_LABEL_CNVT',
 'USER_OBJ_MAP',
 'USR_CODE',
 'USR_CODE_HIST',
 'USR_DEPT',
 'USR_MENU_HIST',
 'USR_TERM',
 'USR_USER_ABSENCE',
 'USR_USER_APPLICATION',
 'USR_USER_DEPT_MAP',
 'WK_HOUR']

In [100]:
# 두개의 유니크한 테이블 명의 교집합을 찾는다
intersection = list(set(asis_col) & set(rev_col))
print( intersection )
print(len(intersection))

['STD_REQ_CONTENTS', 'MSG_SIGN_RSLT', 'MD_OBJ', 'RM_OBJ_INF', 'USR_DEPT', 'STD_CD_VAL', 'MS_CODE', 'MS_MSG', 'MM_LOGIN_HIST', 'MD_COL', 'MM_NOTICE_FILE', 'MM_MAPBIZOBJ', 'MSG_LINE', 'MM_NOTICE', 'MSG_TARGET', 'MD_INST', 'MS_LOCALE', 'RM_COL_INF', 'COPY_T', 'MSG_SIGN_RSLT_DTL', 'MSG_ATTACH', 'REQ_DOC_INFO', 'MMLICENSE', 'MS_TERM', 'MSG_STEP', 'MMMASTER', 'USER_OBJ_MAP', 'MM_CODE', 'STD_CODE']
29

In [97]:
# asis 공통영역에 해당하는 테이블명 리스트에 해당하는 리버스 테이블명이 있으면 filter_rev에 저장.
for i in range(len(rev.index)) :
  if rev['테이블명'][i].upper() in asis_col:
    filter_rev = pd.concat([filter_rev, rev[i:i+1]], ignore_index=True)

  filter_rev

In [98]:
filter_rev

          테이블명          속성명      엔터티명          컬럼명  ...  암호화방법  Level  컬럼 순서 컬럼 표준화
0       copy_t           no    copy_t           no  ...    NaN    NaN      1      0
1       copy_t          no2    copy_t          no2  ...    NaN    NaN      2      0
2       md_col     오브젝트_아이디    md_col       obj_id  ...    NaN    NaN      1      0
3       md_col       컬럼_아이디    md_col       col_id  ...    NaN    NaN      2      0
4       md_col      유효_종료일자    md_col  aval_end_dt  ...    NaN    NaN      3      0
...        ...          ...       ...          ...  ...    ...    ...    ...    ...
1421  usr_dept  last_chg_dt  usr_dept  last_chg_dt  ...    NaN    NaN      5      0
1422  usr_dept    org_order  usr_dept    org_order  ...    NaN    NaN      6      0
1423  usr_dept  dept_tel_no  usr_dept  dept_tel_no  ...    NaN    NaN      7      0
1424  usr_dept  dept_fax_no  usr_dept  dept_fax_no  ...    NaN    NaN      8      0
1425  usr_dept       del_yn  usr_dept       del_yn  ...    NaN    NaN      9      0

[1426 rows x 22 columns]

In [87]:
filter_rev.shape

(713, 22)

In [88]:
asis.shape

(915, 22)

In [89]:
# 삭제된 정보가 202개나 된다?
#검증

filter_table_col = filter_rev['테이블명'].unique().tolist()
filter_table_col

['copy_t',
 'md_col',
 'md_inst',
 'md_obj',
 'mm_code',
 'mm_login_hist',
 'mm_mapbizobj',
 'mm_notice',
 'mm_notice_file',
 'mmlicense',
 'mmmaster',
 'ms_code',
 'ms_locale',
 'ms_msg',
 'ms_term',
 'msg_attach',
 'msg_line',
 'msg_sign_rslt',
 'msg_sign_rslt_dtl',
 'msg_step',
 'msg_target',
 'req_doc_info',
 'rm_col_inf',
 'rm_obj_inf',
 'std_cd_val',
 'std_code',
 'std_req_contents',
 'user_obj_map',
 'usr_dept']

In [91]:
complement  = list(set(asis_col) - set(filter_table_col))
complement

['USR_MENUGRP',
 'DA_COLUMN',
 'USR_GROUP',
 'MM_ATTACH_FILE',
 'MS_MSG',
 'USR_SCR_OBJ',
 'Part',
 'MM_NOTICE_FILE',
 'MM_MAPBIZOBJ',
 'MM_NOTICE',
 'MS_LOCALE',
 'MS_STD_CONFIG',
 'MD_UDP_VAL',
 '주제영역_1',
 'MSG_ATTACH',
 'MM_BIZ_AREA',
 '물리테이블',
 'MS_TERM',
 'MMMASTER',
 'MD_UDP_GRP',
 'DA_ENTITY',
 'DA_ATTRIBUTE',
 'DA_MODELSTRU',
 'USR_USAGE_LOG',
 'STD_REQ_CONTENTS',
 'MAU_ROLE_PRV_REL',
 'MSG_SIGN_RSLT',
 'MM_CODE',
 'USR_USR_ALERT',
 'MS_CODE',
 '게시물',
 'DQ업무영역',
 '부서',
 'USR_EVENT',
 'USR_JOB_EVENT',
 'MSG_TARGET',
 'MAU_PRV_INFO',
 'MD_INST',
 'PRE_MSG_RSLT',
 'RM_COL_INF',
 'MAU_PRV_REL',
 'MS_CFG_LST_VAL',
 'MMLICENSE',
 'STD_DIC',
 'USER_OBJ_MAP',
 'MS_MDL_CONFIG',
 'USR_DAILY_ALERT',
 'USR_USER',
 '모델영역',
 'USR_ROLE_PRIV',
 'IMSI_MD_UDP_REQ',
 'MD_OBJ',
 '주제영역',
 'USR_MENU',
 'DA_TABLE',
 'USR_GROUP_MEMBER',
 'STD_CD_VAL',
 'MM_LOGIN_HIST',
 'MD_COL',
 '표준분류체계_1',
 'MD_UDP_REQ_CONTENTS',
 '응용분류체계',
 '조직정보',
 'COPY_T',
 'REQ_DOC_INFO',
 '작업',
 '인사정보',
 'MS_DB_CONFIG',
 'MS_USR_LANG_MAP',
 'USR_ROLE',
 '표준분류체계',
 'MS_CFG_CLS',
 'MD_UDP_DEF',
 'STD_CODE',
 'RM_OBJ_INF',
 'USR_RCV_EVENT',
 'USR_DEPT',
 'MAU_ROLE_REL',
 '사용자',
 'USR_ALLOC',
 'DQ업무영역_1',
 '역할',
 'MSG_LINE',
 'MS_DB_SRC_LOG',
 'MSG_SIGN_RSLT_DTL',
 'USR_PRIV',
 '메타표준오브젝트',
 'USR_PRIV_SCR_OBJ',
 '인사정보_1',
 'MSG_STEP',
 'MD_UDP_CLSS',
 'MAU_ROLE_INFO']

In [102]:
len(asis['테이블명'].unique())

92